spring:
  datasource:
    url: jdbc:mysql://192.168.0.108:3306/im?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8880
grpc:
  server:
    port: 28880
  client:
    GLOBAL:
      negotiationType: plaintext

mybatis:
  type-aliases-package: com.itrjp.im.uid.worker.entity
  mapper-locations: 'classpath:mapper/*.xml'
