version: '3.8'
services:
  # 长链接服务
  im-connect:
    container_name: im-connect
    build:
      context: im-connect
      dockerfile: Dockerfile
    image: im-connect:latest
    ulimits:
      core: -1
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    environment:
      - JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
    ports:
      - 8080:8080
      - 18080:18080
      - 29090:29090
    networks:
      - im-network
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - consul
  # 分发服务
  im-dispatcher:
    container_name: im-dispatcher
    build:
      context: im-dispatcher
      dockerfile: Dockerfile
    image: im-dispatcher:latest
    ulimits:
      core: -1
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    environment:
      - JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
    ports:
      - 8180:8180
      - 28180:28180
    networks:
      - im-network
    depends_on:
      - kafka1
      - kafka2
      - kafka3
  # 统计服务
  im-stat:
    container_name: im-stat
    build:
      context: im-stat
      dockerfile: Dockerfile
    image: im-stat:latest
    ulimits:
      core: -1
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    environment:
      - JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
    ports:
      - 8280:8280
      - 28280:28280
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      - im-network
  # 消息服务
  im-message:
    container_name: im-message
    build:
      context: im-message
      dockerfile: Dockerfile
    image: im-message:latest
    ulimits:
      core: -1
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    environment:
      - JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
    ports:
      - 8380:8380
      - 28380:28380
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      - im-network
  # 存储服务
  im-storage:
    container_name: im-storage
    build:
      context: im-storage
      dockerfile: Dockerfile
    image: im-storage:latest
    ulimits:
      core: -1
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    environment:
      - JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
    ports:
      - 8480:8480
      - 28480:28480
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      - im-network
  zookeeper1:
    image: zookeeper:3.4
    restart: always
    hostname: zookeeper1
    container_name: zookeeper1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888
    networks:
      - im-network
  zookeeper2:
    image: zookeeper:3.4
    restart: always
    hostname: zookeeper2
    container_name: zookeeper2
    ports:
      - 2182:2182
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888
    networks:
      - im-network
  zookeeper3:
    image: zookeeper:3.4
    restart: always
    hostname: zookeeper3
    container_name: zookeeper3
    ports:
      - 2183:2183
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888
  kafka1:
    image: wurstmeister/kafka:2.12-2.4.1
    restart: always
    hostname: kafka1
    container_name: kafka1
    privileged: true
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    networks:
      - im-network
  kafka2:
    image: wurstmeister/kafka:2.12-2.4.1
    restart: always
    hostname: kafka2
    container_name: kafka2
    privileged: true
    ports:
      - 9093:9093
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka2
      KAFKA_LISTENERS: PLAINTEXT://kafka2:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    networks:
      - im-network
  kafka3:
    image: wurstmeister/kafka:2.12-2.4.1
    restart: always
    hostname: kafka3
    container_name: kafka3
    privileged: true
    ports:
      - 9094:9094
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka3
      KAFKA_LISTENERS: PLAINTEXT://kafka3:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9094
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    external_links:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    networks:
      - im-network
  consul:
    image: consul:1.11.3
    hostname: consul
    ports:
      - 8300:8300
      - 8500:8500
      - 8600:8600
    command: consul agent -dev -ui -client 0.0.0.0 -log-level=INFO
    networks:
      - im-network
networks:
  im-network:
    driver: bridge