DROP TABLE IF EXISTS WORKER_NODE;
CREATE TABLE WORKER_NODE
(
ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'auto increment id',
HOST_NAME VARCHAR(64) NOT NULL COMMENT 'host name',
PORT VARCHAR(64) NOT NULL COMMENT 'port',
TYPE INT NOT NULL COMMENT 'node type: ACTUAL or CONTAINER',
LAUNCH_DATE DATE NOT NULL COMMENT 'launch date',
MODIFIED TIMESTAMP NOT NULL COMMENT 'modified time',
CREATED TIMESTAMP NOT NULL COMMENT 'created time',
PRIMARY KEY(ID)
)
COMMENT='DB WorkerID Assigner for UID Generator',ENGINE = INNODB;

-- im.im_channels definition
DROP TABLE IF EXISTS IM_CHANNELS;
CREATE TABLE IM_CHANNELS (
  ID bigint NOT NULL AUTO_INCREMENT,
  APP_ID char(8) NOT NULL DEFAULT '' COMMENT '应用ID',
  CHANNEL_ID char(11) NOT NULL COMMENT '频道ID',
  FILTER_TYPE int DEFAULT '0' COMMENT '消息过滤类型, 0: 自动, 1: 黑词过滤',
  CHANNEL_LIMIT int DEFAULT '1000' COMMENT '频道限制人数',
  CREATE_TIME timestamp NULL DEFAULT NULL,
  CREATE_USER varchar(255) NULL DEFAULT NULL,
  UPDATE_TIME timestamp NULL DEFAULT NULL,
  UPDATE_USER varchar(255) NULL DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE INDEX IM_CHANNEL_ID_INDEX(CHANNEL_ID ASC) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `im`.`IM_CHANNELS` (`ID`, `APP_ID`, `CHANNEL_ID`, `FILTER_TYPE`, `CHANNEL_LIMIT`, `CREATE_TIME`, `CREATE_USER`, `UPDATE_TIME`, `UPDATE_USER`) VALUES (1, '12345678', 'ch_00000001', 0, 1000, '2022-12-26 23:59:06', 'admin', NULL, NULL);
INSERT INTO `im`.`IM_CHANNELS` (`ID`, `APP_ID`, `CHANNEL_ID`, `FILTER_TYPE`, `CHANNEL_LIMIT`, `CREATE_TIME`, `CREATE_USER`, `UPDATE_TIME`, `UPDATE_USER`) VALUES (2, '12345678', 'ch_00000002', 0, 1000, '2022-12-26 23:59:11', 'admin', NULL, NULL);

DROP TABLE IF EXISTS IM_APPS;
CREATE TABLE IM_APPS (
  ID int NOT NULL AUTO_INCREMENT,
  APP_ID char(8) NOT NULL COMMENT '应用ID',
  APP_NAME varchar(255) NOT NULL DEFAULT '' COMMENT '应用名称',
  CREATE_TIME timestamp NULL DEFAULT NULL,
  CREATE_USER varchar(255) NULL DEFAULT NULL,
  UPDATE_TIME timestamp NULL DEFAULT NULL,
  UPDATE_USER varchar(255) NULL DEFAULT NULL,
  PRIMARY KEY (ID) USING BTREE,
  UNIQUE INDEX IM_APPS_APP_ID_INDEX(APP_ID ASC) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 2 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;
INSERT INTO IM_APPS (ID, APP_ID, APP_NAME, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER) VALUES (1, '12345678', 'test', '2022-12-26 23:44:58', 'admin', NULL, NULL);
