DROP TABLE IF EXISTS WORKER_NODE;
CREATE TABLE WORKER_NODE
(
ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'auto increment id',
HOST_NAME VARCHAR(64) NOT NULL COMMENT 'host name',
PORT VARCHAR(64) NOT NULL COMMENT 'port',
TYPE INT NOT NULL COMMENT 'node type: ACTUAL or CONTAINER',
LAUNCH_DATE DATE NOT NULL COMMENT 'launch date',
MODIFIED TIMESTAMP NOT NULL COMMENT 'modified time',
CREATED TIMESTAMP NOT NULL COMMENT 'created time',
PRIMARY KEY(ID)
)
COMMENT='DB WorkerID Assigner for UID Generator',ENGINE = INNODB;

-- im.im_channels definition
DROP TABLE IF EXISTS IM_CHANNELS;
CREATE TABLE IM_CHANNELS (
  id bigint NOT NULL AUTO_INCREMENT,
  CHANNEL_ID char(10) NOT NULL COMMENT '频道ID',
  FILTER_TYPE int DEFAULT '0' COMMENT '消息过滤类型, 0: 自动, 1: 黑词过滤',
  CHANNEL_LIMIT int DEFAULT '1000' COMMENT '频道限制人数',
  PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;